#配置swagger配置
knife4j:
  production: false #默认是false ,屏蔽所有Swagger的相关资源
  enable: true #是否开启swagger
#swagger公共信息
#swagger.yml
swagger:
  base-packages: com.lemonyliu.controller
  description: 文件项目接口文档
  title: 文件项目接口文档
  license:
  license-url: https://www.lemonyliu.com
  terms-of-service-url: https://www.lemonyliu.com
  contact:
    name: zuoping.liu
    email: zuoping.liu@163.com
    url:
oss:
  endpoint: https://oss-cn-shanghai.aliyuncs.com
  accessKeyId: your_accessKeyId
  accessKeySecret: your_accessKeySecret
  bucketName: your_bucketName
  baseFolder: your_baseFolder

server:
  port: 9090

file:
  path: "C:/Users/MI/Desktop/myalgorithm"
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///trms_data?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: xiaoliu
    password: 960614abcd
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.**.entity
  #typeEnumsPackage: com.qxwz.enums
  global-config:
    # 关闭MP3.0自带的banner
    banner: true
    db-config:
      #主键类型  0:"数据库ID自增", 1:"不操作", 2:"用户输入ID",3:"数字型snowflake", 4:"全局唯一ID UUID", 5:"字符串型snowflake";
      id-type: assign_id
      #字段策略
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_empty
      #驼峰下划线转换
      table-underline: true
      # 逻辑删除配置
      # 逻辑删除全局值（1表示已删除，这也是Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，这也是Mybatis Plus的默认配置）
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
